### ISSUE TITLE
HTTP 401 Unauthorized with bot accounts

### ISSUE THREAD

**Issue by LittleK00PA** [jonas747/discorder#10]
I can sign in perfectly well with a user account, but bot accounts dont work. This is a real shame as i was hoping to be able to chat using a bot.

HTTP 401 Unauthorized, {"code": 0, "message": "401: Unauthorized"}

**Comment by jonas747** [comment]
Add "Bot " in front of the token, e.g: `Bot YourTokenHere`

**Comment by LittleK00PA** [comment]
Yes however this method does not appear to be working, its either due to the text being adjusted to 2 lines (though i doubt it) because of the characters not fitting the text box, or the much more likely one, bearer (the tag for a normal user oauth token) is automatically being placed infront (designating you as a user), because the program automatically places bearer there giving you no choice, placing bot only makes it like this (Authentication: "bearer bot {token}")

**Comment by LittleK00PA** [comment]
its not the second one, putting the window to full size eliminates the text break problem, yet the same lack of ability to log in is displayed

**Comment by jonas747** [comment]
`Bearer` is not for user accounts, that's for oauth2 tokens, there is no prefix for normal user accounts. Bots however use `Bot` as the prefix, i just logged into a bot account using that method, make sure the b in Bot is capitalised and there is a space between Bot and the actual token

**Comment by LittleK00PA** [comment]
B needed to be capitalized lol
