### ISSUE TITLE
Give me my discord details back

### ISSUE THREAD

**Issue by RICKASHEYE** [jonas747/discorder#14]
yes give me my details back i keep getting 404 Not found
Log: 2019/07/05 22:17:28 Trying to log in using email and pa│                                                          │ssword                                                      │                                                          │Log: 2019/07/05 22:17:28 Sucessfully logged in!             │                                                          │Log: 2019/07/05 22:18:16 Error sending typing:  HTTP 404 NOT│                                                          │ FOUND, {"code": 0, "message": "404: Not Found"}            │                                                          │Log: 2019/07/05 22:18:19 Error sending typing:  HTTP 404 NOT│                                                          │ FOUND, {"code": 0, "message": "404: Not Found"}

**Comment by ACA30** [comment]
1. This isn't supported, and in fact violates Discord ToS. This may be a contributor to the fact that it gave you an error 404.
2. The last update to this was 2 years ago, and it isn't being actively developed anymore, as again, it violates Discord ToS.
3. You can't "give details back". That simply isn't a thing. Secondly, I don't believe discorder saves your details, and if it does, it would be client-side.

**Comment by RICKASHEYE** [comment]
what i meant about give details back is that i thought that you stored the data on the creators private storage server or something so they can use my token and impersonate me also i have created a discord client similar to this in C# but it is not recommended because yes it is not supported and it violates the ToS
