### ISSUE TITLE
How to see channel activity

### ISSUE THREAD

**Issue by shrx** [jonas747/discorder#5]
I can select a server and then a channel, and type in a message and send it. But I can't see that my message was received, because I can't figure out how to see the channel activity. Instead of users and messages, there is always just discorder's log displayed. See the screenshot.
![screenshot from 2016-09-07 09 26 28](https://cloud.githubusercontent.com/assets/810337/18303432/5f1935a4-74dd-11e6-868c-c7e560c07d52.png)

**Comment by jonas747** [comment]
You have to mark channels for listening with ctrl-space

**Comment by shrx** [comment]
Ooh, neat. Thanks.
